export const designAspects = [
  'OVERALL',
  'VISUAL_STRUCTURE',
  'COLOR_CONTRAST',
  'POINT_OF_ENTRY',
  'TYPOGRAPHY',
];

export enum EDesignAspect {
  OVERALL = 'OVERALL',
  VISUAL_STRUCTURE = 'VISUAL_STRUCTURE',
  COLOR_CONTRAST = 'COLOR_CONTRAST',
  POINT_OF_ENTRY = 'POINT_OF_ENTRY',
  TYPOGRAPHY = 'TYPOGRAPHY',
}
