export const designAspects = [
  'APPROPRIATENESS',
  'EMPHASIS',
  'ALIGNMENT',
  'HIERARCHY',
  'CONSISTENCY',
  'READABILITY',
  'OVERALL'
];

export enum EDesignAspect {
  APPROPRIATENESS = 'APPROPRIATENESS',
  EMPHASIS = 'EMPHASIS',
  ALIGNMENT = 'ALIGNMENT',
  HIERARCHY = 'HIERARCHY',
  CONSISTENCY = 'CONSISTENCY',
  READABILITY = 'READABILITY',
  OVERALL = 'OVERALL',
}
